basePath: /api/v1
definitions:
  main.Book:
    properties:
      author:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
  description: API for managing books
  title: My Book API
  version: "1.0"
paths:
  /api/v1/books/:
    get:
      description: Get all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Book'
            type: array
      summary: Get all books
    post:
      consumes:
      - application/json
      description: Create a new book
      parameters:
      - description: Book object
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/main.Book'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Book'
      summary: Create a book
  /api/v1/books/{id}:
    delete:
      description: Delete a specific book by ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete a book
    get:
      description: Get a specific book by ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Book'
      summary: Get a book by ID
    put:
      consumes:
      - application/json
      description: Update a specific book by ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      - description: Book object
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/main.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Book'
      summary: Update a book
swagger: "2.0"
